"$schema" = 'https://starship.rs/config-schema.json'

# add_newline=false

format = """
[](color_blue)\
$os\
${custom.instance}\
[](bg:color_orange fg:color_blue)\
$username\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_deep_blue)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_deep_blue bg:color_bg2)\
$docker_context\
$conda\
[](fg:color_bg2 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\

[](color_bg1)\
$status\
[](fg:color_bg1 bg:color_bg2)\
$cmd_duration\
[ ](fg:color_bg2 bg:color_bg1)\
${custom.loadavg_low}\
${custom.loadavg_high}\
[ ](fg:color_bg1)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_text = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg2 = '#665c54'
color_blue = '#00769c'
color_aqua = '#689d6a'
color_green = '#36AE7C'
color_orange = '#e06235'
color_purple = '#C06C84'
color_red = '#EB5353'
color_yellow = '#d79921'
color_deep_blue = '#6256CA'



# [palettes.gruvbox_dark]
# color_text = '#fbf1c7'
# color_bg1 = '#3c3836'
# color_bg2 = '#665c54'
# color_blue = '#1b83b0'
# color_aqua = '#689d6a'
# color_green = '#6fa246'
# color_orange = '#d65d0e'
# color_purple = '#b16286'
# color_red = '#cc241d'
# color_yellow = '#d79921'

[os]
disabled = false
style = "bg:color_blue fg:color_text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_orange fg:color_text"
style_root = "bg:color_orange fg:color_text"
format = '[ $user ]($style)'

[custom.instance]
disabled = false
when = ''
command = "echo instance name"
format = '[ $output ]($style)'
style = "fg:color_text bg:color_blue"

[hostname]
ssh_only = false
format = '[$hostname]($style)'
style = "fg:color_text bg:color_blue"
aliases = { "Xcodes-MacBook-Pro" = " MacBook Pro M1 " }
disabled = false


[directory]
style = "fg:color_text bg:color_yellow"
format = "[ $path ]($style)"
home_symbol = ''
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_text bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_text bg:color_aqua)]($style)'

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_text bg:color_deep_blue)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_text bg:color_deep_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_text bg:color_deep_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_text bg:color_deep_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_text bg:color_deep_blue)]($style)'

[java]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_text bg:color_deep_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_text bg:color_deep_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_text bg:color_deep_blue)]($style)'

[python]
symbol = ""
style = "bg:color_purple"
format = '[[ $symbol( $version)](fg:color_text bg:color_deep_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg2"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg2)]($style)'

[conda]
style = "bg:color_bg2"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg2)]($style)'

[time]
disabled = false
time_format = "%R"
use_12hr = false
style = "bg:color_bg1"
format = '[[  $time ](fg:color_text bg:color_bg1)]($style)'

[cmd_duration]
disabled = false
min_time = 0
show_milliseconds = true
format = '[[ [](fg:color_green bg:color_bg2) $duration ](fg:color_text bg:color_bg2)]($style)'
style= "bg:color_bg2"

[status]
style = 'bg:color_bg1'
symbol = ' [x ](fg:color_red bg:color_bg1)'
success_symbol = ' [](fg:color_green bg:color_bg1)'
not_found_symbol = ' [x ](fg:color_red bg:color_bg1)'
sigint_symbol = ' [ ](fg:color_red bg:color_bg1)'
format = '[$symbol$common_meaning$signal_name$maybe_int ]($style)'

map_symbol = true
disabled = false

[memory_usage]
disabled = false
threshold = 15
format ='$symbol[$ram_pct ram used: $ram ]($style)'
symbol = '[ 󰓅 ]($style)'
style = 'fg:color_red bg:color_bg1'



[custom.loadavg_low]
command = """
loadavg=$(awk '{print $1, $2, $3}' /proc/loadavg)
first_value=$(echo $loadavg | awk '{print $1}' | tr ',' '.')

# Set threshold
threshold=la_threshold

# Compare LA with threshold
if awk "BEGIN {exit !($first_value < $threshold)}"; then
    # If LA < threshold - show only LA1
    printf "󰾆 $first_value"
else

fi
"""
when = ''
format = '[$output ]($style)'
style = 'fg:color_green bg:color_bg1'

[custom.loadavg_high]
command = """
loadavg=$(awk '{print $1, $2, $3}' /proc/loadavg)
first_value=$(echo $loadavg | awk '{print $1}' | tr ',' '.')

# Set threshold
threshold=la_threshold

# Compare LA with threshold
if awk "BEGIN {exit !($first_value > $threshold)}"; then
    # If LA > threshold - show only LA1, LA5 LA15
    printf "  $loadavg"
else

fi
"""
when = ''
format = '[$output ]($style)'
style = 'fg:color_red bg:color_bg1'


[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[x](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'